name: snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/luarocks
        id: luarocks
        env:
          FUNDING_WALLET_CONFIG: ${{ secrets.FUNDING_WALLET_CONFIG }}
        with:
          luarocks-api-key: ${{ secrets.LUAROCKS_API_KEY }}

